### ISSUE TITLE
API error in latest version 1.4.0

### ISSUE THREAD

**Issue by veerap000** [Automattic/vip-block-data-api#77] opened 2024-09-10 16:16 UTC
**Describe the bug**
Sample page API issue/error in version 1.4.0

Using:
New WordPress multisite install with subdirectory (can be also reproduced in default install)
Core version 6.6.1-6.6.2
PHP 8.1
MySQL 8.0.6
Theme: Twenty Twenty-Four 1.2
No other plugins installed

**To Reproduce**
- Install plugin (zip) in WordPress multisite and activate to sub site
- Go to Sample Page URL (https://yourdomain.test/subsite/wp-json/vip-block-data-api/v1/posts/2/blocks) or default "Hello World" post (https://yourdomain.test/subsite/wp-json/vip-block-data-api/v1/posts/1/blocks)

**Expected behavior**
See valid "blocks" structure in JSON.

**Actual behavior**
Returning
```
{
  "code": "vip-block-data-api-parser-error",
  "message": "Error parsing post ID 2: iterator_to_array(): Argument #1 ($iterator) must be of type Traversable, array given",
  "data": {
    "status": 500
  }
}
```
**Block Data API URL**
none (local)

**Version of the plugin**
1.4.0 (https://github.com/Automattic/vip-block-data-api/releases/tag/1.4.0)

**Additional context**
Works OK with version 1.3.0 (zip)

**Comment by alecgeatches** [comment] 2024-09-10 16:59
@veerap000 Thank you for the report, we're looking into this issue now.

**Comment by ingeniumed** [comment] 2024-09-10 21:20
Looks like creating a new release with this issue, auto closed it. So I have re-opened it until it can be confirmed that it's been fixed.

We have cut a new release that should fix this bug. Please let us know if it doesn't 👍🏾

**Comment by veerap000** [comment] 2024-09-11 05:36
Works now with 1.4.1 release. Thanks for really quick fix!

**Comment by ingeniumed** [comment] 2024-09-11 05:41
Perfect, thanks for confirming that. I'll go ahead and close this 👍🏾

**Closed as completed by ingeniumed** 2024-09-11 05:41 UTC
Labels: bug
